# Generated by Django 2.0.2 on 2018-03-01 09:42

from django.db import migrations, models
import django.db.models.deletion
import entities.content_organization.presentation
import entities.content_organization.structures
import entities.evaluation.exercises
import entities.evaluation.quiz
import entities.geometry
import entities.microodas.enigma_comic
import entities.microodas.interactive_video
import entities.microodas.minijuego
import entities.users


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name_field', models.CharField(max_length=100, verbose_name='apellido')),
                ('email_field', models.CharField(max_length=250, verbose_name='correo electrónico')),
                ('password_field', models.CharField(max_length=100, verbose_name='contraseña')),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
            },
            bases=(entities.users.Administrator, models.Model),
        ),
        migrations.CreateModel(
            name='AnswerGivenByLearnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_field', models.CharField(max_length=200, verbose_name='respuesta')),
                ('is_correct_field', models.BooleanField(verbose_name='¿es correcto?')),
            ],
            options={
                'verbose_name': 'respuesta proporcionada por alumno',
                'verbose_name_plural': 'respuestas proporcionadas por alumno',
            },
            bases=(entities.evaluation.quiz.AnswerGivenByLearner, models.Model),
        ),
        migrations.CreateModel(
            name='ContentCreatorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name_field', models.CharField(max_length=100, verbose_name='apellido')),
                ('email_field', models.CharField(max_length=250, verbose_name='correo electrónico')),
                ('password_field', models.CharField(max_length=100, verbose_name='contraseña')),
            ],
            options={
                'verbose_name': 'creador de contenidos',
                'verbose_name_plural': 'creadores de contenido',
            },
            bases=(entities.users.ContentCreator, models.Model),
        ),
        migrations.CreateModel(
            name='DataAnalystModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name_field', models.CharField(max_length=100, verbose_name='apellido')),
                ('email_field', models.CharField(max_length=250, verbose_name='correo electrónico')),
                ('password_field', models.CharField(max_length=100, verbose_name='contraseña')),
            ],
            options={
                'verbose_name': 'analista de datos',
                'verbose_name_plural': 'analistas de datos',
            },
            bases=(entities.users.DataAnalyst, models.Model),
        ),
        migrations.CreateModel(
            name='EngimaComicStaticSceneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_field', models.CharField(choices=[('Escena estática', 'Escena estática'), ('Escena 360', 'Escena 360')], max_length=20, verbose_name='tipo de escena')),
                ('sequence_field', models.PositiveSmallIntegerField(default=0, verbose_name='número de secuencia')),
                ('background_scene_field', models.ImageField(upload_to='', verbose_name='imagen de fondo')),
            ],
            options={
                'verbose_name': 'escena estática de un cómic Enigma',
                'verbose_name_plural': 'escenas estáticas de un cómic Enigma',
            },
            bases=(entities.microodas.enigma_comic.EnigmaComicStaticScene, entities.microodas.enigma_comic.EnigmaComicScene, models.Model),
        ),
        migrations.CreateModel(
            name='EnigmaComicClickableAreaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField(verbose_name='texto')),
                ('is_correct_field', models.BooleanField(default=False, verbose_name='es correcta')),
            ],
            options={
                'verbose_name': 'área cliqueable de un cómic Enigma',
                'verbose_name_plural': 'áreas cliqueables de un cómic Enigma',
            },
            bases=(entities.microodas.enigma_comic.EngimaComicClickableArea, models.Model),
        ),
        migrations.CreateModel(
            name='EnigmaComicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('description_field', models.TextField(blank=True, verbose_name='descripción')),
                ('type_field', models.CharField(choices=[('Video Interactivo', 'Video Interactivo'), ('WikiReto', 'WikiReto'), ('Enigma Comic', 'Enigma Comic'), ('MiniJuego', 'MiniJuego'), ('Organizador', 'Organizador')], max_length=50, verbose_name='tipo')),
                ('default_position_field', models.PositiveSmallIntegerField(default=0, verbose_name='posición por defecto')),
            ],
            options={
                'verbose_name': 'cómic Enigma',
                'verbose_name_plural': 'cómics Enigma',
            },
            bases=(entities.microodas.enigma_comic.EnigmaComic, entities.content_organization.structures.MicroODA, models.Model),
        ),
        migrations.CreateModel(
            name='EnigmaComicS360SceneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_field', models.CharField(choices=[('Escena estática', 'Escena estática'), ('Escena 360', 'Escena 360')], max_length=20, verbose_name='tipo de escena')),
                ('sequence_field', models.PositiveSmallIntegerField(default=0, verbose_name='número de secuencia')),
                ('image_360_field', models.ImageField(upload_to='', verbose_name='imagen 360')),
                ('enigma_comic_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.EnigmaComicModel', verbose_name='cómic Enigma')),
            ],
            options={
                'verbose_name': 'escena 360 de un cómic Enigma',
                'verbose_name_plural': 'escenas 360 de un cómic Enigma',
            },
            bases=(entities.microodas.enigma_comic.EnigmaComicS360Scene, entities.microodas.enigma_comic.EnigmaComicScene, models.Model),
        ),
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('description_field', models.TextField(blank=True, verbose_name='descripción')),
                ('type_field', models.CharField(choices=[('Categorizar', 'Categorizar'), ('Selección de Imágenes', 'Selección de Imágenes'), ('Ordenamiento de Imágenes', 'Ordenamiento de Imágenes')], max_length=50, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'ejercicio',
                'verbose_name_plural': 'ejercicios',
            },
            bases=(entities.evaluation.exercises.Exercise, models.Model),
        ),
        migrations.CreateModel(
            name='ExerciseSolutionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_field', models.CharField(choices=[('Categorizar', 'Categorizar'), ('Selección de Imágenes', 'Selección de Imágenes'), ('Ordenamiento de Imágenes', 'Ordenamiento de Imágenes')], max_length=30, verbose_name='tipo de solución')),
                ('score_field', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='puntuación')),
                ('exercise_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.ExerciseModel', verbose_name='ejercicio')),
            ],
            options={
                'verbose_name': 'solución del ejercicio',
                'verbose_name_plural': 'soluciones del ejercicio',
            },
            bases=(entities.evaluation.exercises.ExerciseSolution, models.Model),
        ),
        migrations.CreateModel(
            name='ForkNodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('type_field', models.CharField(choices=[('Video', 'Video'), ('Bifurcación', 'Bifurcación'), ('Ejercicio', 'Ejercicio')], max_length=50, verbose_name='tipo de nodo')),
                ('image_field', models.ImageField(upload_to='', verbose_name='imagen de fondo')),
            ],
            options={
                'verbose_name': 'nodo de bifurcación para Video Interactivo',
                'verbose_name_plural': 'nodos de bifurcación para Video Interactivo',
            },
            bases=(entities.microodas.interactive_video.VideoNode, entities.microodas.interactive_video.InteractiveVideoNode, models.Model),
        ),
        migrations.CreateModel(
            name='InteractiveVideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('description_field', models.TextField(blank=True, verbose_name='descripción')),
                ('type_field', models.CharField(choices=[('Video Interactivo', 'Video Interactivo'), ('WikiReto', 'WikiReto'), ('Enigma Comic', 'Enigma Comic'), ('MiniJuego', 'MiniJuego'), ('Organizador', 'Organizador')], max_length=50, verbose_name='tipo')),
                ('default_position_field', models.PositiveSmallIntegerField(default=0, verbose_name='posición por defecto')),
            ],
            options={
                'verbose_name': 'microODA',
                'verbose_name_plural': 'microODAs',
                'abstract': False,
            },
            bases=(entities.microodas.interactive_video.InteractiveVideo, entities.content_organization.structures.MicroODA, models.Model),
        ),
        migrations.CreateModel(
            name='LearnerEvaluationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_field', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='puntuación')),
                ('rating_given_by_leaner_field', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='calificación')),
            ],
            options={
                'verbose_name': 'evaluación del alumno',
                'verbose_name_plural': 'evaluaciones del alumno',
            },
            bases=(entities.evaluation.quiz.LearnerEvaluation, models.Model),
        ),
        migrations.CreateModel(
            name='LearnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name_field', models.CharField(max_length=100, verbose_name='apellido')),
                ('email_field', models.CharField(max_length=250, verbose_name='correo electrónico')),
                ('password_field', models.CharField(max_length=100, verbose_name='contraseña')),
            ],
            options={
                'verbose_name': 'alumno',
                'verbose_name_plural': 'alumnos',
            },
            bases=(entities.users.Learner, models.Model),
        ),
        migrations.CreateModel(
            name='MiniJuegoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('description_field', models.TextField(blank=True, verbose_name='descripción')),
                ('type_field', models.CharField(choices=[('Video Interactivo', 'Video Interactivo'), ('WikiReto', 'WikiReto'), ('Enigma Comic', 'Enigma Comic'), ('MiniJuego', 'MiniJuego'), ('Organizador', 'Organizador')], max_length=50, verbose_name='tipo')),
                ('default_position_field', models.PositiveSmallIntegerField(default=0, verbose_name='posición por defecto')),
            ],
            options={
                'verbose_name': 'microODA',
                'verbose_name_plural': 'microODAs',
                'abstract': False,
            },
            bases=(entities.microodas.minijuego.MiniJuego, entities.content_organization.structures.MicroODA, models.Model),
        ),
        migrations.CreateModel(
            name='MiniJuegoSceneItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_positioning_message_field', models.TextField(blank=True, verbose_name='mensaje de éxito')),
                ('incorrect_positioning_message_field', models.TextField(blank=True, verbose_name='mensaje de error')),
                ('image_field', models.ImageField(upload_to='', verbose_name='imagen del sprite')),
                ('correct_row_index_field', models.SmallIntegerField(default=-1, verbose_name='índice de fila correcta')),
                ('correct_column_index_field', models.SmallIntegerField(default=-1, verbose_name='índice de columna correcta')),
            ],
            options={
                'verbose_name': 'item de escena de 0MiniJuego',
                'verbose_name_plural': 'items de escena de MiniJuego',
            },
            bases=(entities.microodas.minijuego.MiniJuegoSceneItem, models.Model),
        ),
        migrations.CreateModel(
            name='MiniJuegoSceneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_field', models.PositiveSmallIntegerField(default=0, verbose_name='número de secuencia')),
                ('minijuego_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.MiniJuegoModel', verbose_name='miniJuego')),
            ],
            options={
                'verbose_name': 'escena de MiniJuego',
                'verbose_name_plural': 'escenas de MiniJuegos',
            },
            bases=(entities.microodas.minijuego.MiniJuegoScene, models.Model),
        ),
        migrations.CreateModel(
            name='NodeLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image_field', models.ImageField(upload_to='', verbose_name='imagen de fondo')),
                ('fork_node_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_links_set', to='studio.ForkNodeModel', verbose_name='nodo de bifurcación')),
                ('target_node_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links_set', to='studio.ForkNodeModel', verbose_name='siguiente nodo')),
            ],
            options={
                'verbose_name': 'enlace de nodos',
                'verbose_name_plural': 'enlaces de nodos',
            },
            bases=(entities.microodas.interactive_video.NodeLink, models.Model),
        ),
        migrations.CreateModel(
            name='ODAModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('description_field', models.TextField(blank=True, verbose_name='descripción')),
                ('icon_field', models.ImageField(upload_to='', verbose_name='ícono')),
            ],
            options={
                'verbose_name': 'ODA',
                'verbose_name_plural': 'ODAs',
            },
            bases=(entities.content_organization.structures.ODA, models.Model),
        ),
        migrations.CreateModel(
            name='Point2DModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_field', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='coordenada x')),
                ('y_field', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='coordenada y')),
            ],
            options={
                'verbose_name': 'coordenadas',
                'verbose_name_plural': 'par de coordenadas',
            },
            bases=(entities.geometry.Point2D, models.Model),
        ),
        migrations.CreateModel(
            name='PossibleAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.CharField(max_length=200, verbose_name='texto')),
                ('is_correct_field', models.BooleanField(verbose_name='¿es correcto?')),
            ],
            options={
                'verbose_name': 'respuesta posible',
                'verbose_name_plural': 'respuestas posibles',
            },
            bases=(entities.evaluation.quiz.PossibleAnswer, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.CharField(max_length=200, verbose_name='texto')),
                ('type_field', models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Open Ended', 'Open Ended')], max_length=20, verbose_name='tipo')),
                ('evaluation_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.LearnerEvaluationModel', verbose_name='evaluación')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
            },
            bases=(entities.evaluation.quiz.Question, models.Model),
        ),
        migrations.CreateModel(
            name='SubworldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('description_field', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'submundo',
                'verbose_name_plural': 'submundos',
            },
            bases=(entities.content_organization.structures.Subworld, models.Model),
        ),
        migrations.CreateModel(
            name='ThemeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('primary_color_field', models.CharField(max_length=6, verbose_name='color primario')),
                ('secondary_color_field', models.CharField(max_length=6, verbose_name='color secundario')),
                ('background_image_field', models.ImageField(upload_to='', verbose_name='imagen de fondo')),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
            },
            bases=(entities.content_organization.presentation.Theme, models.Model),
        ),
        migrations.CreateModel(
            name='VideoNodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=100, verbose_name='nombre')),
                ('type_field', models.CharField(choices=[('Video', 'Video'), ('Bifurcación', 'Bifurcación'), ('Ejercicio', 'Ejercicio')], max_length=50, verbose_name='tipo de nodo')),
                ('source_field', models.URLField(verbose_name='URL')),
                ('close_captions_field', models.TextField(blank=True, verbose_name='subtítulos')),
                ('duration_in_seconds_field', models.PositiveSmallIntegerField(default=0, verbose_name='duración en segundos')),
                ('interactive_video_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.InteractiveVideoModel', verbose_name='video interactivo')),
            ],
            options={
                'verbose_name': 'nodo de video para Video Interactivo',
                'verbose_name_plural': 'nodos de video para Video Interactivo',
            },
            bases=(entities.microodas.interactive_video.VideoNode, entities.microodas.interactive_video.InteractiveVideoNode, models.Model),
        ),
        migrations.CreateModel(
            name='WorldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=150, verbose_name='nombre')),
                ('description_field', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'mundo',
                'verbose_name_plural': 'mundos',
            },
            bases=(entities.content_organization.structures.World, models.Model),
        ),
        migrations.AddField(
            model_name='subworldmodel',
            name='theme_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio.ThemeModel', verbose_name='tema'),
        ),
        migrations.AddField(
            model_name='subworldmodel',
            name='world_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.WorldModel', verbose_name='mundo'),
        ),
        migrations.AddField(
            model_name='possibleanswermodel',
            name='question_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.QuestionModel', verbose_name='pregunta'),
        ),
        migrations.AddField(
            model_name='odamodel',
            name='subworld_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.SubworldModel', verbose_name='submundo'),
        ),
        migrations.AddField(
            model_name='minijuegosceneitemmodel',
            name='scene_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.MiniJuegoSceneModel', verbose_name='escena del MiniJuego'),
        ),
        migrations.AddField(
            model_name='minijuegomodel',
            name='oda_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.ODAModel', verbose_name='ODA'),
        ),
        migrations.AddField(
            model_name='learnerevaluationmodel',
            name='learner_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.LearnerModel', verbose_name='alumno'),
        ),
        migrations.AddField(
            model_name='interactivevideomodel',
            name='oda_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.ODAModel', verbose_name='ODA'),
        ),
        migrations.AddField(
            model_name='forknodemodel',
            name='interactive_video_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.InteractiveVideoModel', verbose_name='video interactivo'),
        ),
        migrations.AddField(
            model_name='forknodemodel',
            name='selected_link_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.NodeLinkModel', verbose_name='nodo elegido'),
        ),
        migrations.AddField(
            model_name='enigmacomicmodel',
            name='exercise_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studio.ExerciseModel', verbose_name='ejercicio'),
        ),
        migrations.AddField(
            model_name='enigmacomicmodel',
            name='oda_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.ODAModel', verbose_name='ODA'),
        ),
        migrations.AddField(
            model_name='enigmacomicclickableareamodel',
            name='point0_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_as_x', to='studio.Point2DModel', verbose_name='punto 0'),
        ),
        migrations.AddField(
            model_name='enigmacomicclickableareamodel',
            name='point1_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_as_y', to='studio.Point2DModel', verbose_name='punto 1'),
        ),
        migrations.AddField(
            model_name='engimacomicstaticscenemodel',
            name='enigma_comic_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.EnigmaComicModel', verbose_name='cómic Enigma'),
        ),
        migrations.AddField(
            model_name='answergivenbylearnermodel',
            name='evaluation_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.LearnerEvaluationModel', verbose_name='evaluación'),
        ),
        migrations.AddField(
            model_name='answergivenbylearnermodel',
            name='question_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.QuestionModel', verbose_name='pregunta'),
        ),
    ]
