# Generated by Django 2.0.3 on 2018-04-05 01:08

from django.db import migrations


# noinspection PyPep8Naming
def add_program_catalogue(apps, schema_editor):
    ProgramModel = apps.get_model('alumnica_model', 'ProgramModel')
    db_alias = schema_editor.connection.alias

    ProgramModel.objects.using(db_alias).create(name_field='Primaria')


def delete_program_catalogue(apps, schema_editor):
    ProgramModel = apps.get_model('alumnica_model', 'ProgramModel')
    db_alias = schema_editor.connection.alias

    ProgramModel.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        # ('alumnica_model', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_program_catalogue, delete_program_catalogue)
    ]
